version: "3.8"
services:
    gateway:
        container_name: gateway
        hostname: gateway
        image: nginx:1.21.0-alpine
        ports:
        - 80:80
        - 443:443
        volumes:
        - ./logs/nginx:/var/log/nginx
        - ./nginx/config-files:/etc/nginx/conf.d/config-files 
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # entrypoint:  
        command: ["nginx", "-g", "daemon off;"] 
        restart: on-failure
    # Mysql database container
    db:
        image: mysql
        container_name: tutorial_db_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - tutorial

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: tutorial_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - tutorial

    # Symfony apache project container
    backend:
        image: ghcr.io/furious-ducks-tiptop/backend:latest
        container_name: backend
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        env_file:
            - .env    
        restart: always
        networks:
            - tutorial
        #entrypoint: /var/www/entrypoint.sh

    frontend:
        image: ghcr.io/furious-ducks-tiptop/frontend:latest
        ports:
        - "3000:3000"
        env_file:
         - .env.production
        

    portainer:
       image: portainer/portainer-ce:latest
       restart: unless-stopped
       networks:
            - tutorial

networks:
    tutorial:

volumes:
    db-data: